#!/usr/bin/env bash
# A script that  groups visitors by IP and HTTP status code, and displays this data. (using only awk)


apache="apache-access.log"
awk '{ print $1, $9 }' $apache | sort | uniq -c | sort -nr
